### ISSUE TITLE
A question about Q1

### ISSUE THREAD

**Issue by JJT-amzn** [zhwenhao-amzn/ELS-MSK-Kinesis#1]
At step 5, there is a error message after running kafka_topics_sizes.sh:

[root@ip-XXXXXXXX]# sh kafka_topics_sizes.sh
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
bash: jq：命令找不到

Do I miss something?

**Comment by zhwenhao-amzn** [comment]
install jq package on your own environment.
sudo yum install jq
